const frenchWords = [
    'bleu',
    'super',
    'autre',
    'bizarre',
    'difficile',
    'drôle',
    'étrange',
    'facile',
    'grave',
    'impossible',
    'jeune',
    'juste',
    'libre',
    'malade',
    'même',
    'pauvre',
    'possible',
    'propre',
    'rouge',
    'sale',
    'simple',
    'tranquille',
    'triste',
    'vide',
    'bonne',
    'toute',
    'doux',
    'faux',
    'français',
    'gros',
    'heureux',
    'mauvais',
    'sérieux',
    'vieux',
    'vrai',
    'ancien',
    'beau',
    'blanc',
    'certain',
    'chaud',
    'cher',
    'clair',
    'content',
    'dernier',
    'désolé',
    'différent',
    'droit',
    'entier',
    'fort',
    'froid',
    'gentil',
    'grand',
    'haut',
    'humain',
    'important',
    'joli',
    'léger',
    'long',
    'meilleur',
    'mort',
    'noir',
    'nouveau',
    'pareil',
    'petit',
    'plein',
    'premier',
    'prêt',
    'prochain',
    'quoi',
    'seul',
    'tout',
    'vert',
    'vivant',
    'Noms communs',
    '',
    'aide',
    'chef',
    'enfant',
    'garde',
    'gauche',
    'geste',
    'gosse',
    'livre',
    'merci',
    'mort',
    'ombre',
    'part',
    'poche',
    'professeur',
    'tour',
    'fois',
    'madame',
    'paix',
    'voix',
    'affaire',
    'année',
    'arme',
    'armée',
    'attention',
    'balle',
    'boîte',
    'bouche',
    'carte',
    'cause',
    'chambre',
    'chance',
    'chose',
    'classe',
    'confiance',
    'couleur',
    'cour',
    'cuisine',
    'dame',
    'dent',
    'droite',
    'école',
    'église',
    'envie',
    'épaule',
    'époque',
    'équipe',
    'erreur',
    'espèce',
    'face',
    'façon',
    'faim',
    'famille',
    'faute',
    'femme',
    'fenêtre',
    'fête',
    'fille',
    'fleur',
    'force',
    'forme',
    'guerre',
    'gueule',
    'habitude',
    'heure',
    'histoire',
    'idée',
    'image',
    'impression',
    'jambe',
    'joie',
    'journée',
    'langue',
    'lettre',
    'lèvre',
    'ligne',
    'lumière',
    'main',
    'maison',
    'maman',
    'manière',
    'marche',
    'merde',
    'mère',
    'minute',
    'musique',
    'nuit',
    'odeur',
    'oreille',
    'parole',
    'partie',
    'peau',
    'peine',
    'pensée',
    'personne',
    'peur',
    'photo',
    'pièce',
    'pierre',
    'place',
    'police',
    'porte',
    'présence',
    'prison',
    'putain',
    'question',
    'raison',
    'réponse',
    'robe',
    'route',
    'salle',
    'scène',
    'seconde',
    'sécurité',
    'semaine',
    'situation',
    'soeur',
    'soirée',
    'sorte',
    'suite',
    'table',
    'terre',
    'tête',
    'vérité',
    'ville',
    'voiture',
    'avis',
    'bois',
    'bras',
    'choix',
    'corps',
    'cours',
    'gars',
    'mois',
    'pays',
    'prix',
    'propos',
    'sens',
    'temps',
    'travers',
    'vieux',
    'accord',
    'agent',
    'amour',
    'appel',
    'arbre',
    'argent',
    'avenir',
    'avion',
    'bateau',
    'bébé',
    'besoin',
    'bonheur',
    'bonjour',
    'bord',
    'boulot',
    'bout',
    'bruit',
    'bureau',
    'café',
    'camp',
    'capitaine',
    'chat',
    'chemin',
    'chéri',
    'cheval',
    'cheveu',
    'chien',
    'ciel',
    'client',
    'cœur',
    'coin',
    'colonel',
    'compte',
    'copain',
    'côté',
    'coup',
    'courant',
    'début',
    'départ',
    'dieu',
    'docteur',
    'doigt',
    'dollar',
    'doute',
    'droit',
    'effet',
    'endroit',
    'ennemi',
    'escalier',
    'esprit',
    'état',
    'être',
    'exemple',
    'fait',
    'film',
    'flic',
    'fond',
    'français',
    'frère',
    'front',
    'garçon',
    'général',
    'genre',
    'goût',
    'gouvernement',
    'grand',
    'groupe',
    'haut',
    'homme',
    'honneur',
    'hôtel',
    'instant',
    'intérêt',
    'intérieur',
    'jardin',
    'jour',
    'journal',
    'lieu',
    'long',
    'maître',
    'mari',
    'mariage',
    'matin',
    'médecin',
    'mètre',
    'milieu',
    'million',
    'moment',
    'monde',
    'monsieur',
    'mouvement',
    'moyen',
    'noir',
    'nouveau',
    'numéro',
    'oeil',
    'oiseau',
    'oncle',
    'ordre',
    'papa',
    'papier',
    'parent',
    'passage',
    'passé',
    'patron',
    'père',
    'petit',
    'peuple',
    'pied',
    'plaisir',
    'plan',
    'point',
    'pouvoir',
    'premier',
    'présent',
    'président',
    'prince',
    'problème',
    'quartier',
    'rapport',
    'regard',
    'reste',
    'retard',
    'retour',
    'rêve',
    'revoir',
    'salut',
    'sang',
    'secret',
    'seigneur',
    'sentiment',
    'service',
    'seul',
    'siècle',
    'signe',
    'silence',
    'soir',
    'soldat',
    'soleil',
    'sourire',
    'souvenir',
    'sujet',
    'téléphone',
    'tout',
    'train',
    'travail',
    'trou',
    'truc',
    'type',
    'vent',
    'ventre',
    'verre',
    'village',
    'visage',
    'voyage',
    'fils',
    'gens',
    'Verbes',
    'abandonner',
    'accepter',
    'accompagner',
    'acheter',
    'adorer',
    'agir',
    'aider',
    'aimer',
    'ajouter',
    'aller',
    'amener',
    'amuser',
    'annoncer',
    'apercevoir',
    'apparaître',
    'appeler',
    'apporter',
    'apprendre',
    'approcher',
    'arranger',
    'arrêter',
    'arriver',
    'asseoir',
    'assurer',
    'attaquer',
    'atteindre',
    'attendre',
    'avancer',
    'avoir',
    'baisser',
    'battre',
    'boire',
    'bouger',
    'brûler',
    'cacher',
    'calmer',
    'casser',
    'cesser',
    'changer',
    'chanter',
    'charger',
    'chercher',
    'choisir',
    'commencer',
    'comprendre',
    'compter',
    'conduire',
    'connaître',
    'continuer',
    'coucher',
    'couper',
    'courir',
    'couvrir',
    'craindre',
    'crier',
    'croire',
    'danser',
    'décider',
    'découvrir',
    'dégager',
    'demander',
    'descendre',
    'désoler',
    'détester',
    'détruire',
    'devenir',
    'deviner',
    'devoir',
    'dire',
    'disparaître',
    'donner',
    'dormir',
    'échapper',
    'écouter',
    'écrire',
    'éloigner',
    'embrasser',
    'emmener',
    'empêcher',
    'emporter',
    'enlever',
    'entendre',
    'entrer',
    'envoyer',
    'espérer',
    'essayer',
    'être',
    'éviter',
    'excuser',
    'exister',
    'expliquer',
    'faire',
    'falloir',
    'fermer',
    'filer',
    'finir',
    'foutre',
    'frapper',
    'gagner',
    'garder',
    'glisser',
    'habiter',
    'ignorer',
    'imaginer',
    'importer',
    'inquiéter',
    'installer',
    'intéresser',
    'inviter',
    'jeter',
    'jouer',
    'jurer',
    'lâcher',
    'laisser',
    'lancer',
    'lever',
    'lire',
    'maintenir',
    'manger',
    'manquer',
    'marcher',
    'marier',
    'mener',
    'mentir',
    'mettre',
    'monter',
    'montrer',
    'mourir',
    'naître',
    'obliger',
    'occuper',
    'offrir',
    'oser',
    'oublier',
    'ouvrir',
    'paraître',
    'parler',
    'partir',
    'passer',
    'payer',
    'penser',
    'perdre',
    'permettre',
    'plaire',
    'pleurer',
    'porter',
    'poser',
    'pousser',
    'pouvoir',
    'préférer',
    'prendre',
    'préparer',
    'présenter',
    'prévenir',
    'prier',
    'promettre',
    'proposer',
    'protéger',
    'quitter',
    'raconter',
    'ramener',
    'rappeler',
    'recevoir',
    'reconnaître',
    'réfléchir',
    'refuser',
    'regarder',
    'rejoindre',
    'remarquer',
    'remettre',
    'remonter',
    'rencontrer',
    'rendre',
    'rentrer',
    'répéter',
    'répondre',
    'reposer',
    'reprendre',
    'ressembler',
    'rester',
    'retenir',
    'retirer',
    'retourner',
    'retrouver',
    'réussir',
    'réveiller',
    'revenir',
    'rêver',
    'revoir',
    'rire',
    'risquer',
    'rouler',
    'sauter',
    'sauver',
    'savoir',
    'sembler',
    'sentir',
    'séparer',
    'serrer',
    'servir',
    'sortir',
    'souffrir',
    'sourire',
    'souvenir',
    'suffire',
    'suivre',
    'taire',
    'tendre',
    'tenir',
    'tenter',
    'terminer',
    'tirer',
    'tomber',
    'toucher',
    'tourner',
    'traîner',
    'traiter',
    'travailler',
    'traverser',
    'tromper',
    'trouver',
    'tuer',
    'utiliser',
    'valoir',
    'vendre',
    'venir',
    'vivre',
    'voir',
    'voler',
    'vouloir',
];

const frenchQuotes = [
    'Nous devons apprendre à vivre ensemble comme des frères, sinon nous allons mourir tous ensemble comme des idiots.',
    "Un peuple prêt à sacrifier un peu de liberté pour un peu de sécurité ne mérite ni l'une ni l'autre, et finit par perdre les deux.",
    'Etre ou ne pas être : telle est la question.',
    "Deux choses sont infinies : l'Univers et la bêtise humaine. Mais, en ce qui concerne l'Univers, je n'en ai pas encore acquis la certitude absolue.",
    "Les sanglots longs des violons de l'automne blessent mon coeur d'une langueur monotone. Tout suffocant et blême, quand sonne l'heure, je me souviens des jours anciens et je pleure.",
    'Aimer les femmes intelligentes est un plaisir de pédéraste.',
    "Les cons, ça ose tout. C'est même à ça qu'on les reconnaît. ",
    "Aux âmes bien nées, la valeur n'attend point le nombre des années.",
    'Ne demandez pas ce que votre pays peut faire pour vous. Demandez ce que vous pouvez faire pour votre pays. ',
    "L'Etat, c'est moi.",
    "Vous pouvez obtenir tout ce que vous désirez dans la vie si vous aidez suffisamment de personnes à obtenir ce qu'elles veulent.",
    "L'inspiration existe, mais il faut qu'elle vous trouve au travail.",
    'Ne vous contentez pas du statu quo. Donnez votre meilleur sur le moment. Ensuite, que cela réussisse ou échoue, vous aurez au moins tout donné.',
    "Montrez-vous, montrez-vous, montrez-vous, et au bout d'un moment, la muse se montrera également.",
    'Celui qui se perd dans sa passion a moins perdu que celui qui perd sa passion.',
    "Si vous voulez que la vie vous sourie, apportez-lui d'abord votre bonne humeur.",
    "Si vous pensez que quelque chose doit exister, si c'est quelque chose que vous allez utiliser vous-même, ne laissez personne vous dissuader de tenter le coup.",
    "Oubliez l'inspiration à un stade initial. Les habitudes sont plus fiables. Les habitudes vous permettront de terminer et de peaufiner vos histoires. Les habitudes représentent la persistance mise en pratique.",
    'Le meilleur chemin est toujours celui qui est le plus direct.',
    "Les batailles qui comptent ne sont pas celles qui sont visibles. Ce sont les luttes à l'intérieur de vous-même - les batailles invisibles et inévitables pour chacun d'entre nous - qui importent.",
    "S'il n'y a pas de difficultés, il n'y a pas de progrès.",
    "Quelqu'un va déclarer : “Je suis le leader !” et s'attendre à ce que tout le monde le suive aveuglément. Selon mon expérience, ce n'est pas ainsi que ça se passe. Les autres vous suivront en fonction de la qualité de vos actions plutôt que la magnitude de vos déclarations.",
    'Le courage est comme un muscle. On le renforce en le travaillant.',
    "Construisez votre succès à partir de vos échecs. Le découragement et l'échec sont les étapes les plus sûres pour parvenir au succès.",
    "Éliminez les distractions sans relâche. N'attendez pas pour faire les choses qui importent, et savourez le temps que vous avez. C'est ce qu'il faut faire quand la vie est courte.",
    "L'indécision fait perdre plus de temps qu'une mauvaise décision.",
    "Si l'objectif prioritaire d'un capitaine était de préserver son navire, il ne le ferait jamais sortir du port.",
    "Même si vous êtes la pêche la plus mure et la plus juteuse au monde, il y aura toujours quelqu'un qui détestera les pêches.",
    'Gardez toujours un petit feu allumé, aussi petit ou caché soit-il.',
    "Rien dans le monde ne pourra remplacer la Persistance. Le talent n'y parviendra pas ; rien n'est plus commun que des hommes talentueux qui ont du mal à réussir. Le génie n'y parviendra pas ; le génie non récompensé est presque un proverbe. L'éducation n'y parviendra pas ; le monde est rempli de fous instruits. Le slogan « Persévère » a résolu et résoudra toujours les problèmes de la race humaine.",
    "Le seul moyen de découvrir les limites du possible est de s'aventurer un peu plus loin dans l'impossible.",
    "Le souci est une mauvaise utilisation de l'imagination.",
    'Le courage est la plus importante de toutes les vertus, car sans courage, on ne peut pratiquer aucune autre vertu de façon cohérente.',
    "Je ne regarde jamais en arrière. Cela détourne l'attention de l'instant présent.",
    "Dans un an, vous allez vous reprocher de ne pas avoir commencé aujourd'hui.",
    "Si nous ressentons de l'insécurité, c'est parce que nous comparons les derrières des coulisses de notre vie avec les meilleures séquences de la vie des autres.",
    "Quelque part, quelque chose d'incroyable attend d'être découvert.",
    "Ne vous laissez pas intimider par l'échec. Il suffit d'avoir raison une seule fois.",
    "Vous portez le passeport qui vous permettra d'atteindre votre propre bonheur.",
    'Fixez-vous des objectifs ambitieux et ne vous arrêtez pas avant de les atteindre.',
    "Prendre la décision d'agir est la chose la plus difficile, le reste n'est qu'une question de ténacité.",
    "Je préfèrerais regretter les choses que j'ai faites plutôt que celles que je n'ai pas faites.",
    "L'échec est le fondement de la réussite.",
    "Je n'essaie pas de danser mieux que tout le monde. J'essaie seulement de m'impressionner moi-même en dansant.",
    'Si vous ne risquez rien, vous prenez encore plus de risque.',
    "C'est inspirant de voir quelqu'un être qui il est vraiment sans éprouver la moindre gêne.",
    "Vous n'allez jamais laisser des empreintes de pas qui durent si vous marchez toujours sur la pointe des pieds.",
    "Si vous n'aimez pas la route sur laquelle vous marchez, commencez à paver une nouvelle route.",
    'Si vous vous sentez nerveux, vous êtes sur le bon chemin.',
    "Ce que vous faites laisse un impact, et vous devez décider du type d'impact que vous souhaiteriez laisser.",
    'Je choisis de faire du reste de ma vie la meilleure partie de ma vie.',
    'Pour être irremplaçable, il faut toujours être différent.',
    "Tout dans la vie peut me pousser à m'arrêter pendant un moment et à réfléchir, et parfois à apprendre.",
    "La passion et le désir des gens pour l'authenticité sont très forts.",
    "Une dose d'efforts supplémentaires peut permettre de surmonter un manque de confiance.",
    'Le doute est le commencement de la sagesse.',
    "Il y a trois façons d'atteindre le succès ultime : la première est d'être gentil. La deuxième est d'être gentil. La troisième est d'être gentil.",
    "Personne ne peut changer le monde sans avoir d'obsession.",
    "J'ai appris il y a longtemps qu'il y a quelque chose de pire que de rater l'objectif, qui est de ne pas passer à l'action.",
    "Prenez vos victoires, quelles qu'elles soient, chérissez-les, utilisez-les, mais ne vous reposez pas dessus.",
    "Il est remarquable de constater l'avantage que certains ont obtenu à long terme en essayant systématiquement de faire preuve de bon sens, au lieu d'essayer d'être très intelligents.",
    'Vous ne pouvez pas être ce gamin qui reste figé en haut du toboggan en réfléchissant. Vous devez glisser.',
    'Quand je crois en quelque chose, je suis comme un chien avec un os à la bouche.',
    'Et vint le jour où le risque de rester serré dans un bourgeon devint plus douloureux que le risque de choisir de fleurir.',
    'Le standard que vous dépassez est le standard que vous acceptez.',
    "La meilleure façon d'apprécier quoi que ce soit est de réaliser que tout peut être perdu.",
    "La vie peut devenir beaucoup plus intéressante une fois que vous réalisez un fait très simple : tout ce que vous appelez la vie autour de vous a été créé par des gens qui n'étaient pas plus intelligents que vous. Et vous pouvez le changer, vous pouvez l'influencer… Une fois que vous aurez compris cela, vous ne serez jamais plus le même.",
    "Le succès s'obtient en traversant les échecs sans perdre son enthousiasme.",
    'Gardez vos yeux sur les étoiles et vos pieds sur terre.',
    "Ne cessez jamais de considérer la vie comme une aventure. Vous n'aurez aucune sécurité à moins de choisir de vivre courageusement, passionnément, avec imagination ; à moins que vous ne puissiez choisir un défi à la place d'une compétence.",
    "La perfection n'est pas atteignable. Mais en recherchant la perfection, il est possible d'atteindre l'excellence.",
    "Trouvez une bonne idée et ne la lâchez plus. Poursuivez-là et mettez-la en œuvre jusqu'à réussir.",
    "L'optimisme est la foi qui mène à la réussite. On ne peut rien faire sans espoir et confiance.",
    "Ne laissez pas le bruit des opinions d'autrui masquer votre voix intérieure.",
    "La vie, c'est comme faire du vélo. Pour garder l'équilibre, il faut continuer à avancer.",
    'Vos actions parlent si fort que je ne peux pas entendre ce que vous dites.',
    "Je n'ai jamais laissé mes études interférer avec mon éducation.",
    'Si vous ne pouvez pas encore faire de grandes choses, faites de petites choses de façon remarquable.',
    'Si vous souhaitez vraiment faire quelque chose, vous trouverez un moyen. Si vous ne le faites pas, vous trouverez une excuse.',
    "Adoptez l'attitude d'un étudiant quel que soit votre niveau de succès, soyez toujours prêt à poser des questions, soyez toujours prêt à apprendre quelque chose de nouveau.",
    "Le succès est une tranquillité d'esprit, qui résulte directement de l'autosatisfaction et du fait de savoir que vous avez fait l'effort de devenir la meilleure version de vous-même.",
    'Assurez-vous de mettre vos pieds au bon endroit, puis tenez-vous solidement.',
    'Laissez votre imagination guider votre vie, plutôt que votre passé.',
    "N'attendez pas de trouver le moment et l'endroit parfaits pour faire votre entrée, vous êtes déjà sur scène.",
    "Plus la difficulté est grande, plus l'on ressent de gloire en la surmontant.",
    'Le courage ne rugit pas toujours. Parfois, le courage se démontre en disant avec une voix calme à la fin de la journée : "Je vais essayer encore demain."',
    'Si les décisions que vous prenez pour investir vos efforts acharnés ne sont pas cohérentes avec la personne que vous souhaitez devenir, vous ne deviendrez jamais cette personne.',
    'Vérifiez que votre pire ennemi ne vit pas entre vos deux oreilles.',
    "C'est un chemin semé d'embuches qui mène au sommet de la grandeur.",
    "L'excellence ne résulte pas d'une impulsion isolée, mais d'une succession de petits éléments qui sont réunis.",
    "Si nous prenons soin des moments, les années prendront soin d'elles-mêmes.",
    "La résilience consiste à aborder l'incertitude avec flexibilité.",
    "Parfois, la magie se produit quand quelqu'un décide de se focaliser sur quelque chose que personne d'autre n'aurait considéré sérieusement.",
    "Ce n'est pas la volonté de réussir qui compte, tout le monde a ça. C'est la volonté de se préparer à réussir qui compte.",
    "Comme un seul pas ne formera pas de chemin sur la terre, une seule pensée ne formera pas de chemin dans l'esprit. Pour former un chemin physique profond, nous marchons sans arrêt. Pour créer un chemin mental profond, nous devons pratiquer sans cesse le type de pensées que nous souhaitons voir prédominer dans nos vies.",
    "N'abandonnez jamais un rêve sur la base du temps qu'il faudra pour le réaliser. Le temps passera de toute façon.",
    "Vous constaterez que l'information est très accessible dans ce monde, et c'est l'une des seules choses qu'une personne peut assimiler à volonté.",
    "L'expérience enseigne de façon contrintuitive, car elle donne le test avant la leçon.",
    "Je n'ai jamais rêvé de succès. J'ai travaillé pour réussir.",
    "Quand on réalise qu'il est possible de continuer d'apprendre sans limites, on commence à apprendre à vivre.",
    'Ne regardez pas vos pieds pour vous assurer que vous effectuez les bons pas. Dansez tout simplement.',
    "Si quelqu'un est assis à l'ombre aujourd'hui, c'est parce que quelqu'un a planté un arbre il y a longtemps.",
    "Il est impossible d'être complètement libre sans libérer l'esprit par la discipline.",
    'Les rivières le savent : rien ne presse. Nous y arriverons tous un jour.',
    "Il y a une vigueur, une force vitale, une énergie, une impulsion en vous que vous transformez en action, et comme il n'y a qu'une seule version de vous-même, cette expression est unique. Si vous la bloquez, elle n'existera jamais sur aucun autre support et sera perdue.",
    "Le succès, c'est obtenir ce que l'on veut. Le bonheur, c'est vouloir ce que l'on obtient.",
    "Petit n'est pas nécessairement synonyme de tremplin. C'est une grande étape en soi.",
    "Celui qui sait se montrer patient peut obtenir ce qu'il veut.",
    'La seule personne qui puisse vous dire "vous ne pouvez pas réussir" est vous-même ; et vous n\'avez pas à écouter.',
    'Vous ne pouvez pas labourer un champ en le retournant dans votre esprit. Pour commencer, commencez.',
    'Mieux vaut être chanceux que bien jouer. ',
    "Perte et gain c'est marchandise ",
    "L'amour est un enfant qui veut être amusé. ",
    "Jamais un homme honteux n'eut une belle amie. ",
    'Mieux vaut être seul que mal accompagné. ',
    'Un livre est un ami qui ne trompe jamais. ',
    'Qui goûte de tout se dégoûte de tout. ',
    "Qui trop s'exalte, trop se prise ; qui trop s'abaisse, il se déprise. ",
    "On n'est jamais mieux servi que par soi-même. ",
    "En matière d'aumône, il faut fermer la bouche et ouvrir le cœur. ",
    'Tant que la bouche est occupée à manger, la panse a de la joie. ',
    "On n'apprend pas à nager à un canard. ",
    'Ce que le loup fait, à la louve plaît. ',
    "La politique n'est que la science de la fourberie. ",
    'Chacun doit porter la peine de sa faute. ',
    'Chacun pour soi, et Dieu pour tous. ',
    "Il n'est chasse que de vieux chiens. ",
    "On ne doit pas faire d'un péché deux pénitences. ",
    "L'adversité doit serrer les nœuds de l'amitié. ",
    "Une grande vengeance est digne d'un grand cœur. ",
    "Un sourire vaut mieux qu'une indignation. ",
    'Mieux vaut suspendre son jugement en plusieurs rencontres. ',
    'À bonne volonté point de chandelle. ',
    'Dis-moi ce que tu lis, et je te dirai ce que tu es. ',
    "Le gibet n'est fait que pour les malheureux. ",
    "On n'a jamais bon marché d'une mauvaise marchandise. ",
    'À bon payeur, bon marché. ',
    'Qui donne se rend maître, et qui reçoit se rend esclave. ',
    'De grand menaceur, peut de fait. ',
    'Qui nul droit à propos ne sait prendre ; nul droit à propos ne doit rendre. ',
    "L'ennui naît de l'oisiveté. ",
    "C'est dur ennui que la contrainte. ",
    'Si jeunesse savait, si vieillesse pouvait. ',
    'Il souvient toujours à Robin de ses flûtes. ',
    'Mieux vaut tuer le diable, que le diable nous tue. ',
    'Il est jaloux comme un gueux de sa besace. ',
    'À petite occasion, le loup prend le mouton. ',
    "Le calme est l'expression du sentiment de la force. ",
    "Qui s'enseigne lui-même, pourrait bien avoir un sot pour maître. ",
    "Où l'hospitalité est belle, le vin est bon. ",
    'La modération est le trésor du sage. ',
    "L'amitié disparaît où l'égalité cesse. ",
    "Pour le cœur d'un libertin, il n'est pas d'éternel chagrin. ",
    'Aux beaux jours souvent succède la tempête. ',
    'La tempérance assaisonne la volupté. ',
    'Le talent a sa pudeur. ',
    "Un sourire n'est pas toujours de bon augure. ",
    "De ses égaux celui qui se fait craindre, ne peut jamais s'en faire aimer. ",
    'La prudence toujours doit régler la valeur. ',
    "Ce n'est pas assez de faire l'aumône, il faut la bien faire. ",
    "N'ayez d'intolérance que vis-à-vis de l'intolérance. ",
    'Chercher midi à quatorze heures. ',
    'Retire-toi dans toi, parais moins, et sois plus. ',
    "Rien n'est plus capable de confondre nos ennemis que la patience dans les injures.",
    'Bien dire fait rire, bien faire fait taire. ',
    'Pâques longtemps désirées sont en un jour tôt passées. ',
    'Parfois de beaux semblants cachent une noirceur. ',
    "L'habit ne fait pas le moine. ",
    "Tout ce qui brille n'est pas or. ",
    'Mieux vaut séduire que sévir. ',
    'Bonne renommée vaut mieux que ceinture dorée. ',
    'Qui fait la faute la boit. ',
    'Qui ne fait son métier doit fermer sa boutique. ',
    'Mieux vaut faire et se repentir, que se repentir et rien faire. ',
    'Qui perd gagne. ',
    "N'a de plaisir qui ne s'en donne. ",
    'Le monde est un spectacle à regarder, et non un problème à résoudre. ',
    'Petit rusé, petit malin. ',
    'Chacun est monsieur de sa qualité. ',
    "L'exactitude est la politesse des rois. ",
    'On est gai le matin, on est pendu le soir. ',
    "L'amour est exclusif, on ne peut aimer en plusieurs endroits à la fois. ",
    'Toujours crie la pire roue du char. ',
    'Qui vole un œuf vole un bœuf. ',
    'À nouveau fait, nouveau conseil. ',
    'Il est bien près du temps des cerises, le temps des cyprès. ',
    'À beau mentir qui vient de loin. ',
    'On ne mélange pas les torchons avec les serviettes. ',
    'À quelque chose sert malheur. ',
    "Le cœur doit conduire l'esprit. ",
];
