const englishWords = [
    'America',
    'Indian',
    'the',
    'of',
    'to',
    'and',
    'a',
    'in',
    'is',
    'it',
    'you',
    'that',
    'he',
    'was',
    'for',
    'on',
    'are',
    'with',
    'as',
    'I',
    'his',
    'they',
    'be',
    'at',
    'one',
    'have',
    'this',
    'from',
    'or',
    'had',
    'by',
    'hot',
    'but',
    'some',
    'what',
    'there',
    'we',
    'can',
    'out',
    'other',
    'were',
    'all',
    'your',
    'when',
    'up',
    'use',
    'word',
    'how',
    'said',
    'an',
    'each',
    'she',
    'which',
    'do',
    'their',
    'time',
    'if',
    'will',
    'way',
    'about',
    'many',
    'then',
    'them',
    'would',
    'write',
    'like',
    'so',
    'these',
    'her',
    'long',
    'make',
    'thing',
    'see',
    'him',
    'two',
    'has',
    'look',
    'more',
    'day',
    'could',
    'go',
    'come',
    'did',
    'my',
    'sound',
    'no',
    'most',
    'number',
    'who',
    'over',
    'know',
    'water',
    'than',
    'call',
    'first',
    'people',
    'may',
    'down',
    'side',
    'been',
    'now',
    'find',
    'any',
    'new',
    'work',
    'part',
    'take',
    'get',
    'place',
    'made',
    'live',
    'where',
    'after',
    'back',
    'little',
    'only',
    'round',
    'man',
    'year',
    'came',
    'show',
    'every',
    'good',
    'me',
    'give',
    'our',
    'under',
    'name',
    'very',
    'through',
    'just',
    'form',
    'much',
    'great',
    'think',
    'say',
    'help',
    'low',
    'line',
    'before',
    'turn',
    'cause',
    'same',
    'mean',
    'differ',
    'move',
    'right',
    'boy',
    'old',
    'too',
    'does',
    'tell',
    'sentence',
    'set',
    'three',
    'want',
    'air',
    'well',
    'also',
    'play',
    'small',
    'end',
    'put',
    'home',
    'read',
    'hand',
    'port',
    'large',
    'spell',
    'add',
    'even',
    'land',
    'here',
    'must',
    'big',
    'high',
    'such',
    'follow',
    'act',
    'why',
    'ask',
    'men',
    'change',
    'went',
    'light',
    'kind',
    'off',
    'need',
    'house',
    'picture',
    'try',
    'us',
    'again',
    'animal',
    'point',
    'mother',
    'world',
    'near',
    'build',
    'self',
    'earth',
    'father',
    'head',
    'stand',
    'own',
    'page',
    'should',
    'country',
    'found',
    'answer',
    'school',
    'grow',
    'study',
    'still',
    'learn',
    'plant',
    'cover',
    'food',
    'sun',
    'four',
    'thought',
    'let',
    'keep',
    'eye',
    'never',
    'last',
    'door',
    'between',
    'city',
    'tree',
    'cross',
    'since',
    'hard',
    'start',
    'might',
    'story',
    'saw',
    'far',
    'sea',
    'draw',
    'left',
    'late',
    'run',
    "don't",
    'while',
    'press',
    'close',
    'night',
    'real',
    'life',
    'few',
    'stop',
    'open',
    'seem',
    'together',
    'next',
    'white',
    'children',
    'begin',
    'got',
    'walk',
    'example',
    'ease',
    'paper',
    'often',
    'always',
    'music',
    'those',
    'both',
    'mark',
    'book',
    'letter',
    'until',
    'mile',
    'river',
    'car',
    'feet',
    'care',
    'second',
    'group',
    'carry',
    'took',
    'rain',
    'eat',
    'room',
    'friend',
    'began',
    'idea',
    'fish',
    'mountain',
    'north',
    'once',
    'base',
    'hear',
    'horse',
    'cut',
    'sure',
    'watch',
    'color',
    'face',
    'wood',
    'main',
    'enough',
    'plain',
    'girl',
    'usual',
    'young',
    'ready',
    'above',
    'ever',
    'red',
    'list',
    'though',
    'feel',
    'talk',
    'bird',
    'soon',
    'body',
    'dog',
    'family',
    'direct',
    'pose',
    'leave',
    'song',
    'measure',
    'state',
    'product',
    'black',
    'short',
    'numeral',
    'class',
    'wind',
    'question',
    'happen',
    'complete',
    'ship',
    'area',
    'half',
    'rock',
    'order',
    'fire',
    'south',
    'problem',
    'piece',
    'told',
    'knew',
    'pass',
    'farm',
    'top',
    'whole',
    'king',
    'size',
    'heard',
    'best',
    'hour',
    'better',
    'true',
    'during',
    'hundred',
    'am',
    'remember',
    'step',
    'early',
    'hold',
    'west',
    'ground',
    'interest',
    'reach',
    'fast',
    'five',
    'sing',
    'listen',
    'six',
    'table',
    'travel',
    'less',
    'morning',
    'ten',
    'simple',
    'several',
    'vowel',
    'toward',
    'war',
    'lay',
    'against',
    'pattern',
    'slow',
    'center',
    'love',
    'person',
    'money',
    'serve',
    'appear',
    'road',
    'map',
    'science',
    'rule',
    'govern',
    'pull',
    'cold',
    'notice',
    'voice',
    'fall',
    'power',
    'town',
    'fine',
    'certain',
    'fly',
    'unit',
    'lead',
    'cry',
    'dark',
    'machine',
    'note',
    'wait',
    'plan',
    'figure',
    'star',
    'box',
    'noun',
    'field',
    'rest',
    'correct',
    'able',
    'pound',
    'done',
    'beauty',
    'drive',
    'stood',
    'contain',
    'front',
    'teach',
    'week',
    'final',
    'gave',
    'green',
    'oh',
    'quick',
    'develop',
    'sleep',
    'warm',
    'free',
    'minute',
    'strong',
    'special',
    'mind',
    'behind',
    'clear',
    'tail',
    'produce',
    'fact',
    'street',
    'inch',
    'lot',
    'nothing',
    'course',
    'stay',
    'wheel',
    'full',
    'force',
    'blue',
    'object',
    'decide',
    'surface',
    'deep',
    'moon',
    'island',
    'foot',
    'yet',
    'busy',
    'test',
    'record',
    'boat',
    'common',
    'gold',
    'possible',
    'plane',
    'age',
    'dry',
    'wonder',
    'laugh',
    'thousand',
    'ago',
    'ran',
    'check',
    'game',
    'shape',
    'yes',
    'hot',
    'miss',
    'brought',
    'heat',
    'snow',
    'bed',
    'bring',
    'sit',
    'perhaps',
    'fill',
    'east',
    'weight',
    'language',
    'among',
];

const englishQuotes = [
    'True terror is to wake up one morning and discover that your high school class is running the country.',
    'Always forgive your enemies; nothing annoys them so much.',
    'Sometimes the road less traveled is less traveled for a reason.',
    'Never go to bed mad. Stay up and fight.',
    'If you can’t be kind, at least be vague.',
    'Misers are no fun to live with, but they make great ancestors.',
    'The statistics on sanity are that one out of every four Americans is suffering from some form of mental illness. Think of your three best friends. If they’re okay, then it’s you.',
    'If you want to know what God thinks of money, just look at the people he gave it to.',
    'Doing nothing is very hard to do. You never know when you’re finished.',
    'In America, there are two classes of travel-first class and with children.',
    'There is no such thing as fun for the whole family.',
    'Just be good and kind to your children. Not only are they the future of the world, they’re the ones who can sign you into a home.',
    'A perfect parent is a person with excellent child-rearing theories and no actual children.',
    'Instead of getting married again, I’m going to find a woman I don’t like and give her a house.',
    'Behind every great man is a woman rolling her eyes.',
    'If you can give your child only one gift, let it be enthusiasm.',
    'If you are not yelling at your kids, you are not spending enough time with them.',
    'Nobody can do for little children what grandparents do. Grandparents sort of sprinkle stardust over the lives of little children.',
    'The simplest toy, one which even the youngest child can operate, is called a grandparent.',
    'The world is extremely interesting to a joyful soul.',
    'Not in doing what you like but in liking what you do is the secret of happiness.',
    'To be without some of the things you want is an indispensable part of happiness.',
    'The older you get the more you realize that kindness is synonymous with happiness.',
    'Happiness makes up in height for what it lacks in length.',
    'Anybody who tells you money can’t buy happiness never had any.',
    'Happiness is good health and a bad memory.',
    'Happiness is having a large, caring, close-knit family in another city.',
    'Don’t wait around for other people to be happy for you. Any happiness you get you’ve got to make yourself.',
    'Happiness often sneaks in through a door you didn’t know you left open.',
    'Every cynic is a sentimentalist under the skin.',
    'Nobody has ever measured, even the poets, how much a heart can hold.',
    'The only thing worse than being talked about is not being talked about.',
    'Man is the only animal that laughs and weeps; for he is the only animal that is struck with the difference between what things are and what they ought to be.',
    'Man is the only animal that blushes-or needs to.',
    'No man who is in a hurry is quite civilized',
    'I would rather sit on a pumpkin and have it all to myself, than to be crowded on a velvet cushion.',
    'The best index to a person’s character is (a) how he treats people who can’t do him any good, and (b) how he treats people who can’t fight back.',
    'I don’t know why people are so keen to put the details of their private life in public; they forget that invisibility is a superpower.',
    'Morality is only moral when it is voluntary.',
    'A man always has two reasons for doing anything-a good reason and the real reason.',
    'The holy passion of friendship is of so sweet and steady and loyal and enduring a nature that it will last through a whole lifetime, if not asked to lend money.',
    'One of the lessons of history is that nothing is often a good thing to do and always a clever thing to say.',
    'It’s not necessary to take a person’s advice to make him feel go',
    'There is only one certainty in life and that is that nothing is certain.',
    'Make it a rule of life never to regret and never to look back. Regret is an appalling waste of energy; you can’t build on it; it’s only good for wallowing.',
    'What do we live for if it is not to make life less difficult for each other.',
    'It is a funny thing about life; if you refuse to accept anything but the best, you very often get it.',
    'There is more to life than increasing its speed.',
    'You cannot do a kindness too soon, for you never know how soon it will be too late.',
    'Life does not have to be perfect to be wonderful.',
    'The beautiful thing about learning is nobody can take it away from you.',
    'My father gave me the best advice of my life. He said, ‘Whatever you do, don’t wake up at 65 years old and think about what you should have done with your life.’',
    'You only have to do a very few things right in your li',
    'There are no hopeless situations; there are only people who have grown hopeless about them.',
    'Pay no attention to what the critics say. A statue has never been erected in honor of a critic.',
    'A problem is a chance for you to do your best.',
    'If your ship doesn’t come in, swim out to it!',
    'Time you enjoy wasting was not wasted.',
    'Worry never robs tomorrow of its sorrow; it only saps today of its strength.',
    'If you are too careful, you are so occupied in being careful that you are sure to stumble over something.',
    'Mistakes are a fact of life. It is the response to the error that counts.',
    'Don’t be afraid to be afraid.',
    'Imagination is more important than knowledge.',
    'The time is always right to do what is right.',
    'You can’t turn back the clock. But you can wind it up again.',
    'Success is falling nine times and getting up ten.',
    'You miss 100 percent of the shots you never take',
    'You’ve got to try your luck at least once a day because you could be going around lucky all day and not even know it',
    'Be like a duck. Calm on the surface but always paddling like the dickens underneath.',
    'The nice thing about being a celebrity is that when you bore people, they think it’s their fault.',
    'Everybody has to be somebody to somebody to be anybody.',
    'People ask me sometimes… When will there be enough women on the court? And my answer is, When there are nine.',
    'Anything’s possible if you’ve got have enough nerve.',
    'Thankfully, perseverance is a great substitute for talent.',
    'If at first you don’t succeed, try, try again. Then quit. There’s no use being a damn fool about it.',
    'You can have it all. You just can’t have it all at once',
    'Play is often talked about as if it were a relief from serious learning. But for children play is serious learning. Play is really the work of childhood.',
    'Age is a high price to pay for maturity.',
    'By the time you’re 80 years old you’ve learned everything. You only have to remember it.',
    'After 30, a body has a mind of its own.',
    'I wish I could tell you it gets better, but it doesn’t get better. You get better.',
    'One of the best parts of growing older? You can flirt all you like since you’ve become harmless.”',
    'Each generation imagines itself to be more intelligent than the one that went before it and wiser than the one that comes after it.',
    'The secret of staying young is to live honestly, eat slowly, and lie about your age.',
];
